### ISSUE TITLE
When will the test code be provided?

### ISSUE THREAD

**Issue by puppy9207** [anymyb/MFDIN-test#1]
I was very surprised by the performance of MSU Benchmark. 
So I'd like to test the MFDIN-L model, which was at the top, when can you provide the code?

**Comment by anymyb** [comment]
@puppy9207 
First of all, thank you for your interest in our work.
Since our paper is still under review, some new versions and codes are not ready to be released yet. Once the paper is reviewed, we will compile all versions of the model and code and inform you then, which will not take long!

**Comment by puppy9207** [comment]
@anymyb 
Personally, I'm going to run it temporarily based on the existing code uploaded.
However, the following problems occurred. Do you happen to know the solution to the problem below?
```
Traceback (most recent call last):
  File "codes/test.py", line 22, in <module>
    model.load_state_dict(net)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MFDIN_OLD1P:
        size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.0.weight: copying a param with shape torch.Size([108, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([216, 64, 3, 3]).
        size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.0.bias: copying a param with shape torch.Size([108]) from checkpoint, the shape in current model is torch.Size([216]).
        size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.2.weight: copying a param with shape torch.Size([108, 108, 3, 3]) from checkpoint, the shape in current model is torch.Size([216, 216, 3, 3]).
        size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.2.bias: copying a param with shape torch.Size([108]) from checkpoint, the shape in current model is torch.Size([216]).
```

**Comment by puppy9207** [comment]
> @anymyb Personally, I'm going to run it temporarily based on the existing code uploaded. However, the following problems occurred. Do you happen to know the solution to the problem below?
> 
> ```
> Traceback (most recent call last):
>   File "codes/test.py", line 22, in <module>
>     model.load_state_dict(net)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for MFDIN_OLD1P:
>         size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.0.weight: copying a param with shape torch.Size([108, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([216, 64, 3, 3]).
>         size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.0.bias: copying a param with shape torch.Size([108]) from checkpoint, the shape in current model is torch.Size([216]).
>         size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.2.weight: copying a param with shape torch.Size([108, 108, 3, 3]) from checkpoint, the shape in current model is torch.Size([216, 216, 3, 3]).
>         size mismatch for AlignMoudle.dcnpack.conv_offset_mask.out_mask_offset.2.bias: copying a param with shape torch.Size([108]) from checkpoint, the shape in current model is torch.Size([216]).
> ```

The default value of the parameter "groups" of the model was 8 and changed to 4 to solve it.
